option(TREAT_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)

macro(enable_extra_compiler_warnings)
	message("Enabled extra warnings for " + "${CMAKE_CURRENT_SOURCE_DIR}")
	if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		add_compile_options(-Wall -Wextra -Wpedantic)
		if(TREAT_WARNINGS_AS_ERRORS)
			add_compile_options(-Werror)
		endif()
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		add_compile_options(/W4)
		if(TREAT_WARNINGS_AS_ERRORS)
			add_compile_options(/WX)
		endif()
	endif()
endmacro()

macro(disable_all_warnings)
	message("Disable all warnings for " + "${CMAKE_CURRENT_SOURCE_DIR}")
	if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		add_compile_options(-w)
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		add_compile_options(/w)
	endif()
endmacro()
