name: "Build & Test"
on: [push]
jobs:
  build_and_test:
    name: "Build & Test"
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang, msvc]
        config: [Debug, Release]
        os: [ubuntu-latest, windows-latest]
        include:
          - compiler: gcc
            config: ASan
            os: ubuntu-latest
          - compiler: gcc
            config: UBSan
            os: ubuntu-latest
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
    runs-on: ${{matrix.os}}
    steps:
      - name: Install needed tools (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install ninja
      - name: Install needed tools and system libraries (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install ninja-build libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
      - uses: actions/checkout@v3
      - name: Set vcpkg environment vars
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
          echo "VCPKG_DEFAULT_BINARY_CACHE=$HOME/vcpkg_cache" >> $GITHUB_ENV
      - name: Create vcpkg cache directory
        run: mkdir ~/vcpkg_cache
      - name: Cache vcpkg binaries
        uses: actions/cache@v3
        with:
          path: ~/vcpkg_cache
          key: ${{matrix.os}}-${{matrix.compiler}}-${{matrix.config}}-${{hashFiles('vcpkg.json')}}
      - name: Set msvc environment vars
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Configure
        run: cmake -S . --preset ${{matrix.compiler}}_vcpkg
      - name: Build
        run: cmake --build build/${{matrix.compiler}}_vcpkg --config ${{matrix.config}}
      - name: Test
        run: |
          build/${{matrix.compiler}}_vcpkg/tests/${{matrix.config}}/tests "[util]" --name util_tests --reporter junit --out test_results_util.xml
          build/${{matrix.compiler}}_vcpkg/tests/${{matrix.config}}/tests "[base]" --name base_tests --reporter junit --out test_results_base.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: "test_results_${{matrix.compiler}}_${{matrix.config}}"
          path: "test_results_*.xml"

  publish_test_results:
    name: "Publish Test Results"
    needs: build_and_test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download results
        uses: actions/download-artifact@v3
        with:
          path: results
      - name: Publish results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: "Test Results 'util'"
          files: "results/**/test_results_util.xml"
      - name: Publish results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: "Test Results 'base'"
          files: "results/**/test_results_base.xml"
